<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TrainingStudio</AssemblyName>
    <Version>0.1.0</Version>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PathMap>$(MSBuildProjectDirectory)=/_/TrainingStudio</PathMap>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
